//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.24 at 11:19:41 PM BST 
//


package com.akhettar.validation.model.xmldiff;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}xml" maxOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dtd" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xml"
})
@XmlRootElement(name = "xmldiff")
public class Xmldiff {

    @XmlElement(required = true)
    protected List<Xml> xml;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String dtd;

    /**
     * Gets the value of the xml property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xml property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXml().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Xml }
     * 
     * 
     */
    public List<Xml> getXml() {
        if (xml == null) {
            xml = new ArrayList<Xml>();
        }
        return this.xml;
    }

    /**
     * Gets the value of the dtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtd() {
        return dtd;
    }

    /**
     * Sets the value of the dtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtd(String value) {
        this.dtd = value;
    }

}
